FROM gcc:12.2-bullseye AS builder
WORKDIR /app
COPY main.cpp .
RUN g++ -O3 -o worker main.cpp

FROM debian:bullseye-slim
RUN useradd -m appuser
WORKDIR /app

COPY --from=builder /app/worker .
RUN chown appuser:appuser worker
USER appuser
CMD ["./worker"]